# Generated by Django 4.0.2 on 2022-02-13 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('forest_name', models.CharField(max_length=100)),
                ('thumbnail_image', models.CharField(max_length=100)),
                ('forest_type', models.CharField(max_length=100)),
                ('brief_description', models.TextField(max_length=250)),
                ('location', models.CharField(max_length=100)),
                ('area_covered', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('long_description', models.TextField(max_length=250)),
                ('health_metrics', models.CharField(max_length=100)),
            ],
        ),
    ]
